package net.tvinci.floramancy.entity.client;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class VesselAnimations {

    public static final Animation ANIM_VESSEL_WAKINGUP = Animation.Builder.create(1.5f)
            .addBoneAnimation("torso",
                                      new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -4f, 0f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.16667f, AnimationHelper.createTranslationalVector(2.5f, -0.33f, 0f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("torso",
                                      new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.16667f, AnimationHelper.createRotationalVector(0f, 0f, -15f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right leg",
                                      new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0.5f, 0f, -5.25f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0.38f, 0f, -3.94f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.625f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right leg",
                                      new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(90f, -10f, 0f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.25f, AnimationHelper.createRotationalVector(67.5f, -7.5f, 0f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.625f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left leg",
                                      new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(-2f, 0f, -6f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left leg",
                                      new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(90f, 32.5f, 0f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                                      new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -4f, 0f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.16667f, AnimationHelper.createTranslationalVector(1f, -0.33f, 0f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                                      new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(-27.5f, 0f, 0f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-18.27f, -1.57f, -4.75f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right arm",
                                      new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(-0.75f, -4f, 0f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.16667f, AnimationHelper.createTranslationalVector(-0.62f, -3.33f, 0f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right arm",
                                      new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(-0.44f, 0.02f, 4.98f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-0.36f, 0.06f, 11.65f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left arm",
                                      new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, -4f, 0f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.16667f, AnimationHelper.createTranslationalVector(3.08f, -1.33f, 0f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left arm",
                                      new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -7.5f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(0.16667f, AnimationHelper.createRotationalVector(0f, 0f, -28.75f),
    Transformation.Interpolations.LINEAR),
            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
    Transformation.Interpolations.LINEAR))).build();
    public static final Animation ANIM_VESSEL_IDLE = Animation.Builder.create(1f).build();
    public static final Animation ANIM_VESSEL_WALKING = Animation.Builder.create(2f).looping()
            .addBoneAnimation("torso",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("torso",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right leg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.5f, -2.75f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 1.25f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-35f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left leg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 1.25f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0.5f, -2.75f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(-35f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, 0f, 3f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, -2.8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.375f, AnimationHelper.createTranslationalVector(0f, 0f, 3f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.75f, AnimationHelper.createTranslationalVector(0f, 0f, -2.8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createRotationalVector(17.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(-11.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.375f, AnimationHelper.createRotationalVector(17.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(-11.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, -1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, -1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(-2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, -1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, -1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(-2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();

}
